- composer.json
- composer.lock
- composer.patches.json
Adding in zaporylie/composer-drupal-optimizations to speed things up a bit. Also, removing an old patch that no longer applies to Drupal core. Misc other cleanup.
> Composertweaks

- web/sites/default/config/default/user.role.steering_committee.yml
I tweaked the perms on this. I think this is what you are asking for, but let me know if anything else needs to be removed/added.
> config: steering_committee update perms

- .github/actions/dingorunner/entrypoint.sh
- .github/workflows/updates.yml
- blt/src/Blt/Plugin/Commands/AmpCommands.php
Change github updates action to only run the update without the behat tests. Then the PR will trigger the behat tests.
> GitHub updates

- composer.lock
> [Composer] drupal/token

- composer.lock
access : 1.0.x-dev c6365cf => 1.0.x-dev 26a871c
> [Composer] amp/access

- web/sites/default/config/default/views.view.resources.yml
https://cyberteamportal.atlassian.net/browse/D8-583
> Resources view: adding sorting D8-583

- composer.lock
masquerade : 2.0.0-beta4 => 2.0.0-rc1
> [Composer] drupal/masquerade

- .gitignore
- blt/src/Blt/Plugin/Commands/AmpCommands.php
Add github token to landosetup()
> Blt amp commands

- web/sites/default/config/default/block.block.views_block__match_engagement_view_block_2.yml
- web/sites/default/config/default/views.view.match_engagement_view.yml
for https://cyberteamportal.atlassian.net/browse/D8-913
> update my engagements title

- web/sites/default/config/default/config_split.config_split.local.yml
- web/sites/default/config/default/core.extension.yml
- web/sites/default/config/local/tfa.settings.yml
This should get past the first amp behat test.
> tfa: split config to disable on local

- web/sites/default/config/default/webform.webform.affinity_group_request.yml
for https://cyberteamportal.atlassian.net/browse/D8-671
> affinity group request - remove approved checkbox

- web/sites/default/config/default/webform.webform_options.rt_categories.yml
for https://cyberteamportal.atlassian.net/browse/D8-902
> RT - add couple more access categories

- web/sites/default/config/default/webform.webform.resource.yml
for https://cyberteamportal.atlassian.net/browse/D8-910
> new role for approving resources for affinity groups

- web/sites/default/config/default/webform.webform_options.rt_categories.yml
- web/sites/default/config/default/webform.webform_options.rt_resources.yml
For https://cyberteamportal.atlassian.net/browse/D8-930 and https://cyberteamportal.atlassian.net/browse/D8-932
> Adding ACCESS-Operations-Security-Accounts & Delta

- web/sites/default/config/default/views.view.access_news.yml
- web/sites/default/config/default/views.view.affinity_group.yml
- web/themes/custom/accesstheme/scss/style.scss
https://cyberteamportal.atlassian.net/browse/D8-715
> access_group: adding news to access groups D8-715

- tests/behat/features/Hannah/affinity-group-page.feature
My first pull request for Affinity Group Page
> Affinity Group Page Feature Test

- tests/behat/features/templates/People-Indiv-Page.feature
- tests/behat/features/templates/People-List-View-Test.feature
- tests/behat/features/templates/connect-ci.feature
- tests/behat/features/templates/footer.feature
- tests/behat/features/templates/form-contact.feature
- tests/behat/features/templates/form-project.feature
- tests/behat/features/templates/form-request-affinity.feature
- tests/behat/features/templates/form-resource.feature
- tests/behat/features/templates/form-tags.feature
- tests/behat/features/templates/form-ticket.feature
- tests/behat/features/templates/menu-unauth.feature
- tests/behat/features/templates/people-card.feature
- tests/behat/features/templates/quick-links-auth
- tests/behat/features/templates/quick-links-unauth.feature
PR for People Page (List View)
> Behat laheara

- composer.lock
> [Composer] drupal/core

- tests/behat/features/templates/Form-Blog-Page.feature
- tests/behat/features/templates/Form-Recources-Page.feature
- tests/behat/features/templates/Get-Help-Page.feature
- tests/behat/features/templates/Indie-Resource-Page.feature
- tests/behat/features/templates/Projects-Engagement-page.feature
- tests/behat/features/templates/affinity-group-page.feature
- tests/behat/features/wip/Form-Blog-Page.feature
- tests/behat/features/wip/Form-Projects-Engagement-Page.feature
- tests/behat/features/wip/Form-Recources-Page.feature
- tests/behat/features/wip/Resource-Page.feature
- tests/behat/features/wip/affinity-group-page.feature
Fixed up the Affinity Group Page
> Behat hannah 2

- tests/behat/features/Hannah/affinity-group-page.feature
- tests/behat/features/templates/form-add-project.feature
- tests/behat/features/templates/form-request-affinity.feature
- tests/behat/features/templates/form-resource.feature
- tests/behat/features/templates/node-add-tagged-blog-post.feature
- tests/behat/features/templates/people-card.feature
- tests/behat/features/templates/tags.feature
I should have renamed this branch!  This PR is primarily a new behat test of the Add-Project webform
> Jasper behat rename cyberteam to nect

- blt/src/Blt/Plugin/Commands/AmpCommands.php
- composer.json
- composer.lock
- tests/behat/features/nect/1-nect-domaindefault.feature
- web/sites/default/config/default/core.extension.yml
- web/sites/default/config/default/maillog.settings.yml
- web/sites/default/config/default/views.view.maillog_overview.yml
- web/sites/default/config/local/mailsystem.settings.yml
- web/sites/default/config/local/system.mail.yml
misnamed branch -- this is config changes for split and maillog
> Behat jasper passing

- tests/behat/features/Jasper/node-add-tagged-blog-post.feature
- tests/behat/features/careers/1-careers-domaindefault.feature
- tests/behat/features/ky/logged-out-request-tag-FAILING.feature
- tests/behat/features/templates/add-tag-to-blog-post.feature
- tests/behat/features/templates/node-add-tagged-blog-post.feature
- tests/behat/features/templates/tags-no-entries.feature
Ready for review / merge -- a few more tests.
> Behat jasper

- tests/behat/features/bootstrap/Drupal/FeatureContext.php
- tests/behat/features/templates/projects_individual.feature
- tests/behat/features/templates/tags-individual.feature
Added a "wait for page to be loaded"
> Behat wait for page to load

- web/sites/default/config/default/views.view.cc_applications.yml
> D8-1032 -- only allow leadership team members to see CC pending applications

- web/themes/custom/accesstheme/scss/style.scss
> D8-1055 -- set a min-width for ag icons columns so they don't shrink too small

- web/sites/default/config/default/block.block.addevents.yml
- web/sites/default/config/default/block.block.eventsnodetypelinkbacktoeventsview.yml
> events - add link back to /events

- web/sites/default/config/default/views.view.affinity_group.yml
For https://cyberteamportal.atlassian.net/browse/D8-1049
Ready for review
> affinity groups -- only show people for community groups

- web/sites/default/config/default/views.view.cc_applications.yml
> cc-applications, give access to roles administrator and campuschampionsadmin

- blt/src/Blt/Plugin/Commands/AmpCommands.php
- tests/behat/features/bootstrap/Drupal/FeatureContext.php
- tests/behat/features/champ/champ-front-unauth.feature
- tests/behat/features/champ/champ-homepage_logo.feature
- tests/behat/features/templates/affinity_groups-request.feature
- tests/behat/features/templates/homepage_logo.feature
- tests/behat/features/templates/tags-individual.feature
also added a homepage_logo.feature example use of it
> behat - add a "image should load" custom step

- web/sites/default/config/default/block.block.views_block__resources_block_1.yml
- web/sites/default/config/default/block.block.views_block__resources_block_3.yml
block 1 appears for ACCESS Support domain
block 3 appears for all other domains.  (notice the `negate` flag is true)
ready for review
> D8-1130 -- configure tag's resources block to appear properly

- tests/behat/features/templates/affinity_groups-request.feature
- web/sites/default/config/default/webform.webform.affinity_group_request.yml
ready for review!  It's set to merge into Hannah-4
> Ag coordinators

- web/modules/custom/campuschampions/src/Plugin/Action/ApproveCCAction.php
- web/modules/custom/campuschampions/src/Plugin/Action/DeclineCCAction.php
- web/sites/default/config/default/views.view.cc_applications.yml
- web/sites/default/config/default/webform.webform.join_campus_champions.yml
for https://cyberteamportal.atlassian.net/browse/D8-1087
ready for review
> Approval process for campus champions applications (D8-1087)

- web/sites/default/config/default/user.role.campuschampionsadmin.yml
> CC declines -- give CCAdmins permission to decline

- web/sites/default/config/default/block.block.accesslogingraphic.yml
for https://cyberteamportal.atlassian.net/browse/D8-1126, on login page, move infographic down
> on login screen, move infographic down -- D8-1126

- web/sites/default/config/default/views.view.affinity_group.yml
ready for review -- in conjunction with access changes
> Add title & description of CiDeR resources to AG view

- web/sites/default/config/default/core.entity_form_display.node.affinity_group.default.yml
- web/sites/default/config/default/webform.webform_options.rt_resources.yml
> ticket webform - remove IU from queue list -- D8-1159

- blt/src/Blt/Plugin/Commands/AmpCommands.php
- tests/behat/features/Jasper/verify_image_tests.feature
- tests/behat/features/bootstrap/Drupal/FeatureContext.php
- tests/behat/features/templates/homepage_logo.feature
@a-pasquale  -- here are some more ways to verify website images.  More notes on https://cyberteamportal.atlassian.net/browse/D8-1120
> behat - more image verification (D8-1120)

- web/sites/default/config/default/webform.webform.affinity_group_request.yml
ready for review for https://cyberteamportal.atlassian.net/browse/D8-1139
> AG request form - fix email field - D8-1139

- .github/workflows/behat.yml
- blt/src/Blt/Plugin/Commands/AmpCommands.php
- Separated each site into their own job for tests
- Added a default to the 'sites' input and this can no longer be submitted blank
> GitHub action update

- web/sites/default/config/default/views.view.recurring_events_event_instances.yml
> display future events in ascending order (soonest first)

- web/sites/default/config/default/dblog.settings.yml
> Increase saved logging messages to 10,000

- composer.lock
phpstan-deprecation-rules : 1.0.0 => 1.1.1
> [Composer] phpstan/phpstan-deprecation-rules

- tests/behat/features/Hannah/match-plus-unauth.feature
- tests/behat/features/asp/community-unauth.feature
- tests/behat/features/asp/match-plus-unauth.feature
- tests/behat/features/cci/cci-homepage.feature
> Behat jasper 2 2 23

- tests/behat/features/asp/navigation_bar_footer.feature
one tiny change -- let's see if tests pass
> add a wait for an observed ajax faiilure

- web/sites/default/config/default/webform.webform_options.rt_categories.yml
ready for review.  this branch does not have a comma in its name, hopefully tests will pass.
the new list is below. look good, including the ordering?
```
ACCESS-Website: 'ACCESS Website'
ACCESS-Support-OnDemand: OnDemand
ACCESS-Support-Pegasus: Pegasus
ACCESS-Support-Training: Training
ACCESS-Support-CSSN: CSSN
ACCESS-Metrics: Metrics
ACCESS-Operations-Security-Accounts: 'ACCESS Accounts'
ACCESS-WG-Roadmaps: 'ACCESS Roadmaps'
ACCESS-Operations-Security: 'ACCESS Security'
ACCESS-Operations-Feedback: 'Operations Feedback'
ACCESS-Operations-Services: 'Operations Services'
ACCESS-Operations-StudentProgram: 'Operations Student Program'
ACCESS-XDMoD: XDMoD
0-Help: Other
```
> ticketing -- rename access security -- D8-1229

- .lando.yml
hi @protitude  -- my lando was still on 8.0 without the change to .lando.yml in this PR.  Andrew asked me to create this PR for your review.
> with andrew, added line to get php 8.1 for my lando

- web/sites/default/config/default/field.storage.user.field_cider_resources.yml
field is hidden on register form
> Permission-type from public to custom so

- composer.json
- composer.lock
- web/sites/default/config/default/block.block.communitypersonablock.yml
- web/sites/default/config/default/block.block.communitypersonacssnstaticblock.yml
- web/sites/default/config/default/core.extension.yml
Once the access pull request is merged https://github.com/necyberteam/access/pull/51 this module will need the composer.json file updated to reflect the proper branch for amp/access.
> Md 1283 Persona page

- web/sites/default/config/default/block.block.views_block__resources_block_1_2.yml
- web/sites/default/config/default/views.view.resource.yml
- web/sites/default/config/default/views.view.resources.yml
In this request, the voting display was removed.
> D8-1290 - Resources Page

- composer.lock
- web/sites/default/config/default/block.block.accessresourcespageintro.yml
- web/sites/default/config/default/block.block.accesstheme_content.yml
- web/sites/default/config/default/block.block.accesstheme_help.yml
- web/sites/default/config/default/block.block.accesstheme_local_actions.yml
- web/sites/default/config/default/block.block.accesstheme_local_tasks.yml
- web/sites/default/config/default/block.block.accesstheme_messages.yml
- web/sites/default/config/default/block.block.eventsnodetypelinkbacktoeventsview.yml
- web/sites/default/config/default/block.block.interestsdescription_2.yml
- web/sites/default/config/default/block.block.newsandeventsblock.yml
- web/sites/default/config/default/block.block.newsnodetypelinkbacktonewsview.yml
- web/sites/default/config/default/block.block.outagesblock.yml
- web/sites/default/config/default/block.block.skillsdescription_2.yml
- web/sites/default/config/default/block.block.views_block__access_news_block_1.yml
- web/sites/default/config/default/block.block.views_block__access_news_block_3.yml
- web/sites/default/config/default/block.block.views_block__affinity_groups_with_tag_block_2.yml
- web/sites/default/config/default/block.block.views_block__match_engagement_view_block_1.yml
- web/sites/default/config/default/block.block.views_block__match_engagement_view_block_2.yml
- web/sites/default/config/default/block.block.views_block__match_engagement_view_block_3.yml
- web/sites/default/config/default/block.block.views_block__match_engagement_view_block_4.yml
- web/sites/default/config/default/block.block.views_block__match_engagement_view_block_5.yml
- web/sites/default/config/default/block.block.views_block__match_engagement_view_block_6.yml
- web/sites/default/config/default/block.block.views_block__recurring_events_event_instances_block_1.yml
- web/sites/default/config/default/block.block.views_block__recurring_events_event_instances_block_2.yml
- web/sites/default/config/default/block.block.views_block__recurring_events_event_series_block_1.yml
- web/sites/default/config/default/block.block.views_block__resources_block_1_2.yml
- web/sites/default/config/default/views.view.access_news.yml
- web/sites/default/config/default/views.view.recurring_events_event_instances.yml
- web/themes/custom/accesstheme/scss/style.scss
see notes on https://cyberteamportal.atlassian.net/browse/D8-1204
> first cut at adding news and events to frong page

- web/themes/nect-theme/templates/comment.html.twig
- web/themes/nect-theme/templates/links--comment.html.twig
- web/themes/nect-theme/templates/menu--account.html.twig
- web/themes/nect-theme/templates/page--node--223.html.twig
- web/themes/nect-theme/templates/page--node--434.html.twig
- web/themes/nect-theme/templates/page.html.twig
- web/themes/nect-theme/templates/views-view--term_from_ask_ci.html.twig
- web/themes/nect-theme/templates/views-view-unformatted--region_select_card.html.twig
- web/themes/nect-theme/templates/views-view-unformatted--region_select_list.html.twig
- web/themes/nect-theme/templates/webform-section.html.twig
Minor fixes to decorative icons and links without text for accessibility. No visual changes.
> Fix nect accessibility

- composer.lock
- web/themes/custom/accesstheme/scss/style.scss
- web/themes/custom/accesstheme/templates/page.html.twig
Fix for news and events block on ASP homepage, adjusting the bootstrap classes.
> Mobile ASP fixes

- web/sites/default/config/default/webform.webform.edit_your_cssn_roles.yml
Ready for review.  
Small change to existing Join CSSN form, addition of Edit CSSN Roles form
> CSSN webform changes & addition - D8-1302

- tests/behat/features/asp/knowledge-base-unauth.feature
- tests/behat/features/asp/pegasus-unauth.feature
- tests/behat/features/champ/champ-homepage.feature
- tests/behat/features/nect/1-nect-domaindefault.feature
- tests/behat/features/templates/resources-1-add-admin.feature
- tests/behat/features/templates/resources-auth.feature
- tests/behat/features/templates/resources-unauth.feature
- tests/behat/features/templates/tags-individual.feature
> Behat jasper fixes 3 24

- composer.json
- composer.lock
- web/sites/default/config/default/user.role.match_sc.yml
The new match_sc role is created in the config. The access module will need to be switched back to 1.0.x in the composer file once it's merged: https://github.com/necyberteam/access/pull/65
> access: 1.0.x-dev b169ff9 => dev-d8-1370 11d8b9f d8-1370

- web/sites/default/config/default/core.entity_form_display.node.match_engagement.default.yml
- web/sites/default/config/default/user.role.match_sc.yml
I programmatically added email user, published checkbox, and email user checkbox to the access_match_engagment.module
Updated user role config from prod
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1402
Access module PR:
https://github.com/necyberteam/access/pull/68
> match_sc role can edit and see promotion options for MATCH Engagements (md-1402)

- README.md
Test run workflow on pr merge.
> Readme: tweak

- README.md
> Readme: tweak #nobuild

- tests/behat/features/asp/1-asp-domaindefault.feature
- tests/behat/features/asp/events-unauth.feature
- tests/behat/features/asp/match-plus-unauth.feature
- tests/behat/features/asp/ondemand-unauth.feature
- tests/behat/features/asp/pegasus-unauth.feature
- tests/behat/features/templates/account-edit-auth.feature
- tests/behat/features/templates/contact-user-auth.feature
- tests/behat/features/templates/people-indie-auth.feature
- tests/behat/features/templates/people-indie-unauth.feature
- tests/behat/features/templates/tags-individual.feature
- web/sites/default/config/default/nodeaccess.settings.yml
- web/sites/default/config/default/system.action.user_add_role_action.match_sc.yml
- web/sites/default/config/default/system.action.user_remove_role_action.match_sc.yml
This is a merge of `jasper-behat-4-12` (various fixed to get tests to pass) and `d8-1426` (restoring a missing view).  Doing this to see if all test now pass.
d8-1426
#557 and #558
> Jasper behat 4 13

- tests/behat/features/asp/1-asp-domaindefault.feature
- tests/behat/features/asp/events-unauth.feature
- tests/behat/features/asp/match-plus-unauth.feature
- tests/behat/features/asp/ondemand-unauth.feature
- tests/behat/features/asp/pegasus-unauth.feature
- tests/behat/features/templates/account-edit-auth.feature
- tests/behat/features/templates/contact-user-auth.feature
- tests/behat/features/templates/people-indie-auth.feature
- tests/behat/features/templates/people-indie-unauth.feature
> Jasper behat 4 12

- tests/behat/features/templates/account-edit-auth.feature
- web/sites/default/config/default/views.view.add_skill.yml
Change title from Add Skills to Add Expertise to bring this inline with other word changes.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1427
(no multidev site provided for small change)
> Add Expertise title added to view instead of add skill d8-1427

- composer.json
- composer.lock
- web/sites/default/config/default/nodeaccess.settings.yml
- web/sites/default/config/default/system.action.user_add_role_action.cip.yml
- web/sites/default/config/default/system.action.user_remove_role_action.cip.yml
- web/sites/default/config/default/user.role.authenticated.yml
- web/sites/default/config/default/user.role.cip.yml
- web/sites/default/config/default/webform.webform.join_the_cssn_network.yml
- web/sites/default/config/local/user.role.authenticated.yml
ACCESS PR: https://github.com/necyberteam/access/pull/71
- https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1341
- https://cyberteamportal.atlassian.net/browse/D8-1417
- https://cyberteamportal.atlassian.net/browse/D8-1340
This also resolves in d8-1340 and d8-1405
I ran a spot check on the current submissions and my update seemed to do the trick: https://md-1340-accessmatch.pantheonsite.io/admin/structure/webform/manage/join_the_cssn_network/results/submissions
> access: 1.0.x-dev d28c9c1 => dev-d8-1340 147db06

- composer.json
- composer.lock
- web/sites/default/config/default/core.extension.yml
- web/sites/default/config/default/views.view.match_engagement_view.yml
Copied changes from #565 because of merge conflict in composer.lock
https://cyberteamportal.atlassian.net/browse/D8-1441
n/a
> Use custom order to sort engagements

- web/sites/default/config/default/views.view.match_interested_users.yml
On the match interested users page, update the link for the user from user/edit to community-persona
https://cyberteamportal.atlassian.net/browse/D8-1438
> d8-1438 - link match interested users to community persona

- web/sites/default/config/default/views.view.match_engagement_view.yml
remove stick-on-top filter for engagements
https://cyberteamportal.atlassian.net/browse/D8-1436
> d8-1436 - remove stick-on-top filter for engagements

- .github/workflows/behat.yml
- blt/src/Blt/Plugin/Commands/AmpCommands.php
Update behat command to stream in real-time
https://cyberteamportal.atlassian.net/browse/D8-1463
> blt: update behat command to stream in realtime d8-1463

- composer.lock
- web/themes/custom/accesstheme/js/accesstheme.js
- web/themes/custom/accesstheme/scss/_variables_bootstrap.scss
- web/themes/custom/accesstheme/scss/style.scss
- web/themes/custom/accesstheme/templates/page.html.twig
> Asp-theme-updates

- web/sites/default/config/default/webform.webform.edit_your_cssn_roles.yml
Changing "Edit your CSSN roles" into "Edit your roles" Since the roles shown are not specific to the CSSN roles.
https://cyberteamportal.atlassian.net/browse/D8-1476
> Edit your roles change

- blt/src/Blt/Plugin/Commands/AmpCommands.php
Remove one line of stale logging from behat AmpCommands.php
https://cyberteamportal.atlassian.net/browse/D8-1495
> very minor change to testing script, remove stale logging

- web/sites/default/config/default/views.view.cssn_members.yml
Restrict access to the CSSN Members view to the match_pm role.
https://cyberteamportal.atlassian.net/browse/D8-1469
n/a
n/a
> CSSN Members view restricted to match_pm role.

- tests/behat/features/templates/affinity_groups-request.feature
> Working on Affinity Group Webform Errors

- web/sites/default/config/default/mail_login.settings.yml
2nd better way to fix missing text on password reset form
https://cyberteamportal.atlassian.net/browse/D8-1392
> d8-1392 -- fix password reset by updating mail_login config

- web/sites/default/config/default/user.role.ccmnet_pm.yml
- web/sites/default/config/default/webform.webform.ccmnet_mentors_contact.yml
- web/sites/default/config/default/webform.webform.get_updates_about_ccmnet.yml
- web/sites/default/config/default/webform.webform.join_ccmnet.yml
Make CCMNet webform submissions accessible/visible to CCMNet PMs
Also add shortcuts to those forms to shortcut bar.
https://cyberteamportal.atlassian.net/browse/D8-1469
> D8 1469  Give CCMNet PMs access to 3 webforms

- tests/behat/features/asp/cssn_form_request.feature
- tests/behat/features/asp/navigation_bar_footer.feature
Adding test that will go through the CSSN form and select options. The test will then verify that the roles have been added onto the community persona page.
https://cyberteamportal.atlassian.net/browse/D8-1465
> CSSN Form Test for ASP Domain

- .github/actions/dingorunner/entrypoint.sh
- .github/workflows/main.yml
- blt/src/Blt/Plugin/Commands/PmdCommands.php
- web/themes/custom/accesstheme/templates/page.html.twig
Re-order sidebars and main content on mobile.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1477
> accesstheme: reorder sidebars/main d8-1477

- .devcontainer/Dockerfile
- composer.json
- composer.lock
- tests/behat/features/asp/announcements-unauth.feature
- web/sites/default/config/default/block.block.exposedformaccess_newsblock_1.yml
- web/sites/default/config/default/block.block.requestanewspostblock.yml
- web/sites/default/config/default/block.block.views_block__access_news_block_1.yml
- web/sites/default/config/default/block.block.views_block__access_news_block_3.yml
- web/sites/default/config/default/core.entity_view_display.node.match_engagement.default.yml
- web/sites/default/config/default/node.type.access_news.yml
- web/sites/default/config/default/views.view.access_news.yml
Rebrand news as announcements
https://cyberteamportal.atlassian.net/browse/D8-1494
https://github.com/necyberteam/access/pull/94
http://md-1494-accessmatch.pantheonsite.io
> Rebrand news as announcements

- web/sites/default/config/default/user.role.match_sc.yml
Give MATCH SC users access to shortcuts.  
https://cyberteamportal.atlassian.net/browse/D8-1435
> grant Match SC access to shortcuts

- .github/actions/dingorunner/entrypoint.sh
- .github/workflows/main.yml
- blt/src/Blt/Plugin/Commands/PmdCommands.php
- web/sites/default/config/default/views.view.recurring_events_event_instances.yml
Fix events views.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1514
http://md-1514-accessmatch.pantheonsite.io
> views: recurring_event_instances fix field aggregation d8-1514

- web/sites/default/config/default/field.field.node.access_organization.field_carnegie_code.yml
- web/sites/default/config/default/field.field.node.access_organization.field_country.yml
- web/sites/default/config/default/field.field.node.access_organization.field_is_active.yml
- web/sites/default/config/default/field.field.node.access_organization.field_is_msi.yml
- web/sites/default/config/default/field.field.node.access_organization.field_latitude.yml
- web/sites/default/config/default/field.field.node.access_organization.field_longitude.yml
- web/sites/default/config/default/field.field.node.access_organization.field_org_type.yml
- web/sites/default/config/default/field.field.node.access_organization.field_organization_abbrev.yml
- web/sites/default/config/default/field.field.node.access_organization.field_organization_name.yml
- web/sites/default/config/default/field.field.node.access_organization.field_organization_phone.yml
- web/sites/default/config/default/field.field.node.access_organization.field_organization_url.yml
- web/sites/default/config/default/field.field.node.access_organization.field_state.yml
- web/sites/default/config/default/node.type.access_organization.yml
Add config YML for ACCESS Organization content type
https://cyberteamportal.atlassian.net/browse/D8-1490
https://github.com/necyberteam/access/pull/99
> feat: ACCESS Organization content type config

- web/sites/default/config/default/automated_cron.settings.yml
Set drupal's cron to never run.
https://cyberteamportal.atlassian.net/browse/D8-1522
> d8-1522 -- set cron to never run

- web/sites/default/config/default/field.field.node.access_organization.field_organization_id.yml
- web/sites/default/config/default/field.storage.node.field_country.yml
- web/sites/default/config/default/field.storage.node.field_is_active.yml
- web/sites/default/config/default/field.storage.node.field_is_msi.yml
- web/sites/default/config/default/field.storage.node.field_latitude.yml
- web/sites/default/config/default/field.storage.node.field_longitude.yml
- web/sites/default/config/default/field.storage.node.field_org_type.yml
- web/sites/default/config/default/field.storage.node.field_organization_abbrev.yml
- web/sites/default/config/default/field.storage.node.field_organization_id.yml
- web/sites/default/config/default/field.storage.node.field_organization_name.yml
- web/sites/default/config/default/field.storage.node.field_organization_phone.yml
- web/sites/default/config/default/field.storage.node.field_organization_url.yml
- web/sites/default/config/default/field.storage.node.field_state.yml
> ACCESS Organization content type

- web/sites/default/config/default/block.block.exposedformpeople_card_viewcard_access_cssn.yml
- web/sites/default/config/default/block.block.exposedformpeople_card_viewcard_campus_champions.yml
- web/sites/default/config/default/block.block.exposedformpeople_card_viewcard_careers.yml
- web/sites/default/config/default/block.block.exposedformpeople_card_viewcard_greatplains.yml
- web/sites/default/config/default/block.block.exposedformpeople_card_viewcard_kentucky.yml
- web/sites/default/config/default/block.block.exposedformpeople_card_viewcard_mines.yml
- web/sites/default/config/default/block.block.exposedformpeople_card_viewcard_northeast.yml
- web/sites/default/config/default/block.block.exposedformpeople_card_viewcard_rmacc.yml
- web/sites/default/config/default/block.block.exposedformpeople_card_viewcard_sweeter.yml
- web/sites/default/config/default/block.block.exposedformpeople_card_viewcard_trecis.yml
- web/sites/default/config/default/block.block.exposedformpeople_list_viewlist_access_cssn.yml
- web/sites/default/config/default/block.block.exposedformpeople_list_viewlist_all.yml
- web/sites/default/config/default/block.block.exposedformpeople_list_viewlist_campus_champions.yml
- web/sites/default/config/default/block.block.exposedformpeople_list_viewlist_careers.yml
- web/sites/default/config/default/block.block.exposedformpeople_list_viewlist_greatplains.yml
- web/sites/default/config/default/block.block.exposedformpeople_list_viewlist_kentucky.yml
- web/sites/default/config/default/block.block.exposedformpeople_list_viewlist_mines.yml
- web/sites/default/config/default/block.block.exposedformpeople_list_viewlist_northeast.yml
- web/sites/default/config/default/block.block.exposedformpeople_list_viewlist_rmacc.yml
- web/sites/default/config/default/block.block.exposedformpeople_list_viewlist_trecis.yml
- web/sites/default/config/default/block.block.views_block__people_card_view_card_access_cssn.yml
- web/sites/default/config/default/block.block.views_block__people_list_view_list_access_cssn.yml
- web/sites/default/config/default/views.view.people_card_view.yml
- web/sites/default/config/default/views.view.people_list_view.yml
Add ACCESS CSSN to region filters for people card & list views.
https://cyberteamportal.atlassian.net/browse/D8-1518
> d8-1518 -- add ACCESS CSSN to region filters

- blt/src/Blt/Plugin/Commands/AmpCommands.php
- tests/behat/features/cci/cci-homepage.feature
Minor tweaks / cleanup from other behat work on [PR #606](https://github.com/necyberteam/cyberteam_drupal/pull/606)
https://github.com/necyberteam/cyberteam_drupal/pull/606
> Jasper behat 5 18

- web/sites/default/config/default/block.block.exposedformresourcespage_1_2.yml
- web/themes/custom/accesstheme/scss/style.scss
Adding in the skill levels onto the CI Links page and also fixing the CSS for the section.
https://cyberteamportal.atlassian.net/browse/D8-1382
n/a
> D8 1382|ci links

- composer.lock
- web/sites/default/config/default/content_moderation_notifications.content_moderation_notification.engagement_accepted.yml
- web/sites/default/config/default/content_moderation_notifications.content_moderation_notification.engagement_review_requested.yml
- web/sites/default/config/default/content_moderation_notifications.content_moderation_notification.needs_adjustment.yml
- web/sites/default/config/default/content_moderation_notifications.content_moderation_notification.published.yml
- web/sites/default/config/default/content_moderation_notifications.content_moderation_notification.review_requested.yml
- web/sites/default/config/default/views.view.access_news.yml
For email notifications of updates to news and events, fixes to the email body links to the news or events
https://cyberteamportal.atlassian.net/browse/D8-1351
https://github.com/necyberteam/access/pull/106
> D8 1351   bad links in news notifications

- composer.json
- composer.lock
- web/sites/default/config/default/core.entity_view_display.eventseries.default.default.yml
Affinity group email formatting fixes for events and news
please see details at d8-1395 PR
https://cyberteamportal.atlassian.net/browse/D8-1395
https://github.com/necyberteam/access/pull/107
http://md-1395-accessmatch.pantheonsite.io
> Affinity group email formatting fixes for events and news

- web/sites/default/config/default/core.extension.yml
Update config to disable domain_chosen_select
https://cyberteamportal.atlassian.net/browse/D8-1538
> domain_chosen_select: disable module d8-1538

- tests/behat/features/asp/MATCHPremier-unauth.feature
Test for matchpremier engagement was failing
N/A
N/A
N/A
> Fix match premier test

- web/sites/default/config/default/views.view.tagged_news_block.yml
Replacing News w/ Announcements within the Tagged News Block Section
https://cyberteamportal.atlassian.net/browse/D8-1531
> Replacing News w/ Announcements

- composer.json
- composer.lock
- web/themes/custom/accesstheme/scss/_variables_bootstrap.scss
- web/themes/custom/accesstheme/scss/style.scss
CSS styles for tags
n/a
n/a
n/a
> CSS styles for tags

- composer.json
- composer.lock
> June 2 Sprint

- web/sites/default/config/default/views.view.affinity_group.yml
Update affinity group button to view members.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1533?filter=myopenissues
> view.affinity_group: update button to view members d8-1533

- web/sites/default/config/default/field.field.user.user.field_cv_resume.yml
Adding /resume to the beginning of the CV upload directory.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1547
> config: update user CV file location d8-1547

- composer.json
- composer.lock
Install the Campus Champions theme before adding blocks to it.
n/a
http://md-1503-accessmatch.pantheonsite.io
> Install Campus Champions theme

- web/sites/default/config/default/pfdp.pfdp_directory._webform.yml
Make private/webform accessible to everyone.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1571?filter=myopenissues
> pfdp: make private/webform accissible to all d8-1571

- .devcontainer/codespaces.sh
- composer.lock
- tests/behat/features/asp/about-support-unauth.feature
- tests/behat/features/asp/outages-unauth.feature
- web/sites/default/config/default/webform.webform.affinity_group_request.yml
- web/themes/custom/accesstheme/js/accesstheme.js
- web/themes/custom/accesstheme/scss/style.scss
> June 23 Sprint

- tests/behat/features/asp/MATCHPremier-unauth.feature
Removing parts of test that are no longer relevant.
https://cyberteamportal.atlassian.net/browse/D8-1612
> Removing parts of test that are no longer there

- tests/behat/features/templates/registration_pages.feature
Changed the page location to /people/card
https://cyberteamportal.atlassian.net/browse/D8-1629
> correcting page location

- tests/behat/features/asp/community.feature
Renamed the file 
Enabled Certain section that failed in previous testing
https://cyberteamportal.atlassian.net/browse/D8-1600
> Renamed and Enabled Section community.feature

- composer.lock
> tfa : 1.0.0 => 1.1.0

- web/themes/custom/accesstheme/scss/style.scss
- web/themes/nect-theme/css/style.css
Adding in glossary CSS to both themes
https://cyberteamportal.atlassian.net/browse/D8-1468
> Glossary CSS addition

- composer.patches.json
- web/sites/default/config/default/core.extension.yml
- web/sites/default/config/default/editor.editor.basic_html.yml
- web/sites/default/config/default/editor.editor.full_html.yml
- web/sites/default/config/default/filter.format.basic_html.yml
- web/sites/default/config/default/filter.format.full_html.yml
Switch to CKeditor 5.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1641?filter=myopenissues
http://md-1641-accessmatch.pantheonsite.io
> Md 1641 - CKeditor 5

- tests/behat/features/asp/knowledge-base-unauth.feature
Collapse button in FAQ section of knowledge base needed to be fixed
https://cyberteamportal.atlassian.net/browse/D8-1607
> Fixing collaspe button in FAQ

- web/sites/default/config/default/node.type.affinity_group.yml
Remove preview on affinity group.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1656
> config: affinity_group disable preview d8-1656

- web/sites/default/config/default/views.view.match_engagement_view.yml
add Status: line to Match Engagements cards using the html in the global text field (blocks)
https://cyberteamportal.atlassian.net/browse/D8-1546
no
http://md-1546-accessmatch.pantheonsite.io
- [x ] I have checked that the PR is ready to be merged
- [ x] I have reviewed the DIFF and checked that the changes are as expected
- [x ] I have assigned myself or someone else to review the PR
> Status line on Match Engagement cards

- web/sites/default/config/default/webform.webform.ccmnet_mentors_contact.yml
- web/sites/default/config/default/webform.webform.get_updates_about_ccmnet.yml
Adding in updates to CCM files
https://cyberteamportal.atlassian.net/browse/D8-1662
> D8 1662|config

- tests/behat/features/asp/events-unauth.feature
Added lines to select "apply" button
https://cyberteamportal.atlassian.net/browse/D8-1602
http://md-{{ D8-1602 }}-accessmatch.pantheonsite.io
> selected apply button D8-1602

- tests/behat/features/asp/affinity-groups-unauth.feature
Following is failing in github only when running entire test suite (not when running just asp on github)
https://cyberteamportal.atlassian.net/browse/D8-1597
> Testing file on Github to see error

- tests/behat/features/asp/homepage-unauth.feature
Image testing was added to the homepage of ACCESS Support
https://cyberteamportal.atlassian.net/browse/D8-1606
> Adding image testing to homepage

- tests/behat/features/asp/announcement-tags.feature
- tests/behat/features/asp/events-tags.feature
- tests/behat/features/asp/knowledge-base-unauth.feature
- tests/behat/features/asp/match-plus-unauth.feature
- tests/behat/features/asp/nav-unauth.feature
- tests/behat/features/asp/ondemand-unauth.feature
This a redo of previous PR that got old & stale.   Migrated the previous work to this branch.
> Redo  d8 1329|tags page

- tests/behat/features/asp/events-unauth.feature
- tests/behat/features/asp/homepage-unauth.feature
redo of https://github.com/necyberteam/cyberteam_drupal/pull/705 - asp homepage & events fixes
https://cyberteamportal.atlassian.net/browse/D8-1605
> Redo  d8 1605|links

- tests/behat/features/cci/cci-homepage.feature
redo of PR #698 - testing cci homepage
https://cyberteamportal.atlassian.net/browse/D8-1616
https://github.com/necyberteam/cyberteam_drupal/pull/698
> d8-1616 -- cci homepage links

- tests/behat/features/asp/affinity-groups-unauth.feature
- tests/behat/features/asp/affinity_groups-request.feature
- tests/behat/features/asp/asp-ci-links-indie-auth.feature
redo of https://github.com/necyberteam/cyberteam_drupal/pull/689.  
Add test testing Request an Affinity Group link takes you to login and then a webform to request a new Affinity Group | affinity-group-unauth
https://cyberteamportal.atlassian.net/browse/D8-1598
https://github.com/necyberteam/cyberteam_drupal/pull/689
> Redo  d8 1598|affinity group testing

- tests/behat/features/templates/projects-1-submit-admin.feature
- tests/behat/features/templates/projects-engage-auth.feature
- tests/behat/features/templates/projects-individual.feature
- tests/behat/features/templates/projects-remove-individual.feature
- tests/behat/features/templates/projects-unauth.feature
some improvements for project testing
https://cyberteamportal.atlassian.net/browse/D8-1628
https://github.com/necyberteam/cyberteam_drupal/pull/691
> d8-1628 - improvements to project testing

- tests/behat/features/asp/asp-edit-cssn-roles-auth.feature
- tests/behat/features/asp/match-engagements-submissions-auth.feature
- tests/behat/features/asp/match-plus-unauth.feature
- tests/behat/features/asp/pegasus-unauth.feature
various behat fixes, including a redo of D8-1572
https://cyberteamportal.atlassian.net/browse/D8-1572
https://github.com/necyberteam/cyberteam_drupal/pull/683
> Jasper behat batch 7 31

- tests/behat/features/asp/events-unauth.feature
- tests/behat/features/asp/pegasus-unauth.feature
Adding in more testing for past events test
https://cyberteamportal.atlassian.net/browse/D8-1690
> Adding more parts to past events test

- tests/behat/features/asp/cssn-members.feature
- tests/behat/features/asp/pegasus-unauth.feature
Adding in testing for CSSN Members page
https://cyberteamportal.atlassian.net/browse/D8-1732
> Adding in small test for cssn members test

- tests/behat/features/templates/projects-1-submit-admin.feature
- tests/behat/features/templates/projects-individual.feature
Fixing projects test
had merge issues, so redoing the work with this PR
https://cyberteamportal.atlassian.net/browse/D8-1626
https://github.com/necyberteam/cyberteam_drupal/pull/761
https://github.com/necyberteam/cyberteam_drupal/pull/716
> d8-1626 -- behat - project testing updates

- blt/src/Blt/Plugin/Commands/AmpCommands.php
> Behat update test runner for subfolders

- composer.lock
- composer.patches.json
> Module update

- tests/behat/features/templates/code-of-conduct.feature
- tests/behat/features/templates/help-desk.feature
- tests/behat/features/templates/projects-1-submit-admin.feature
Creating test for code of conduct and help desk pages
https://cyberteamportal.atlassian.net/browse/D8-1682
https://cyberteamportal.atlassian.net/browse/D8-1737
> Creating test for code of conduct and helpdesk

- blt/md/md-1520
- web/modules/custom/campuschampions/src/Plugin/Action/ApproveCCAction.php
Assign proper roles to users approved at /cc-applications
https://cyberteamportal.atlassian.net/browse/D8-1520
http://md-1520-accessmatch.pantheonsite.io
> campusChampions: add user role on status approval d8-1520

- web/sites/default/config/default/core.entity_view_display.node.access_active_resources_from_cid.default.yml
- web/sites/default/config/default/views.view.cider_resources_on_ag_groups.yml
Adding view to Cider resources pages that are referenced on Affinity Groups. Looks like we hit our limit on MD sites so the link below might not work.
https://cyberteamportal.atlassian.net/browse/D8-1798
http://md-1798-accessmatch.pantheonsite.io
> cider: add referenced AG groups 📖 md-1798

- composer.json
- composer.lock
- web/sites/default/config/default/block.block.communitypersonablock_2.yml
- web/sites/default/config/default/block.block.communitypersonablock_3.yml
- web/themes/custom/accesstheme/templates/affinity_group/field--node--field-coordinator--affinity-group.html.twig
- web/themes/nect-theme/templates/field--node--field-coordinator--affinity-group.html.twig
- web/themes/nect-theme/templates/page.html.twig
Community Persona blocks on Nect and CC themes.  Move the sidebar to the left on these themes.
On Affinity Group, link coordinator name to community persona page instead of user profile
https://cyberteamportal.atlassian.net/browse/D8-1792
https://cyberteamportal.atlassian.net/browse/D8-1793
Yes, d8-1792 for Access and Cyberteam Theme
http://md-1792-accessmatch.pantheonsite.io
- [ x] I have checked that the PR is ready to be merged
- [ x] I have reviewed the DIFF and checked that the changes are as expected
- [x ] I have assigned myself or someone else to review the PR
> Community Persona blocks on Nect and CC themes + link to CP on Affinity Group. Md 1792

- tests/behat/features/asp/ccmnet-auth.feature
- tests/behat/features/templates/ccmnet-auth.feature
Adding in test to go through and submit a CCMNET submission
https://cyberteamportal.atlassian.net/browse/D8-1765
> Adding in the CCMNET Test

- tests/behat/features/asp/match-engagements-submissions-auth.feature
Testing for match engagement submissions needs to be made for ACCESS Support.
This covers the MATCH PM, MATCH SC, and administrator roles
https://cyberteamportal.atlassian.net/browse/D8-1685
> Behat testing needed for /match-engagements-submissions route

- tests/behat/features/templates/people-card-auth.feature
Filter by role test and afinity group testing needs to be fixed within people-card-auth.feature
https://cyberteamportal.atlassian.net/browse/D8-1625
> Fixing filter by role test

- composer.json
- composer.lock
Remove change_pwd_page module from composer.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1821
> change_pwd_page: removed d8-1821

- tests/behat/features/asp/homepage/homepage_submenus.feature
- tests/behat/features/asp/homepage/navigation_bar_footer.feature
- tests/behat/features/asp/homepage/universal_navigation.feature
- tests/behat/features/bootstrap/Drupal/FeatureContext.php
Added custom behat steps to verify submenus, and using that to verify ASP submenus.  
Removed some inline TODOs.
> verify ASP submenus, update TODOs

- web/sites/default/config/default/views.view.recurring_events_event_series.yml
Fixing event series view.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1822
http://md-1822-accessmatch.pantheonsite.io
> config: event series view fix d8-1822

- tests/behat/features/asp/cssn/cssn.feature
- tests/behat/features/asp/events/events-unauth.feature
Test Apply button within events-unauth.feature in the filter by section
https://cyberteamportal.atlassian.net/browse/D8-1602
> Adding in test for APPLY button in filter section

- tests/behat/features/asp/cssn/cssn.feature
- tests/behat/features/asp/homepage/asp-social.feature
- tests/behat/features/asp/homepage/homepage.feature
- tests/behat/features/asp/ondemand-unauth.feature
- tests/behat/features/cci/cci-homepage.feature
- tests/behat/features/templates/homepage/homepage_quick-links-auth.feature
Ready for review.
Misc. fixes to tests, and getting all tests to pass.
> Jasper behat 8 30

- tests/behat/features/asp/community_persona.feature
this test requires amp_dev install script is getting properly run on github -- last time i checked, it did not seem to be working
> rechecking if community-persona test is working

- blt/md/md-1833
- web/sites/default/config/default/block.block.frontbuttons.yml
- web/sites/default/config/default/block.block.frontbuttonsloggedin.yml
Change order of blocks on the front page on necyberteam, great plains, careers, kentucky.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1833
> config: move frontbuttons into projects section d8-1833

- tests/behat/features/asp/cssn/cssn.feature
- tests/behat/features/asp/engagements/match-engagements-submissions-auth.feature
- tests/behat/features/asp/engagements/match-plus_researcher.feature
Updating some of Hannah's work to test creating a MATCH-Plus engagement.  
Ready for review
https://cyberteamportal.atlassian.net/browse/D8-1824
> Update tests for creating a MATCH-Plus engagement.  Redo for "d8 1824 match"

- tests/behat/features/careers/careers-projects-1-submit-admin.feature
- tests/behat/features/champ/champ-projects-1-submit-admin.feature
- tests/behat/features/gpc/gpc-projects-1-submit-admin.feature
- tests/behat/features/ky/ky-projects-1-submit-admin.feature
- tests/behat/features/nect/nect-projects-1-submit-admin.feature
- tests/behat/features/templates/projects/projects-1-submit-admin.feature
*This test is still a WIP*
GPC has different line in projects form compared to other domains
https://cyberteamportal.atlassian.net/browse/D8-1800
> Adding separate testing for project form diff

- .github/workflows/behat.yml
- tests/behat/features/asp/homepage/navigation_bar_footer.feature
- tests/behat/features/bootstrap/Drupal/FeatureContext.php
Making sure all tests pass, now with sanitized database.
> Behat 9 7 all tests pass

- tests/behat/features/asp/engagements/match-engagements-submissions-auth.feature
redo of https://github.com/necyberteam/cyberteam_drupal/pull/828
verify engagement submissions page
https://github.com/necyberteam/cyberteam_drupal/pull/828
> behat - d8-1572 - migrate mackenzie's work

- tests/behat/features/asp/xdmod_unauth.feature
This PR is all set to be reviewed!
XDMoD page needs behat testing for ACCESS (/xdmod)
https://cyberteamportal.atlassian.net/browse/D8-1698
> Commiting xdmod test to another branch

- web/themes/custom/accesstheme/scss/style.scss
Adding md-full-width to replace customizations added to the bg-light class
> accesstheme: add md-full-width

- web/sites/default/config/default/block.block.careersdencalltoaction.yml
- web/themes/custom/accesstheme/scss/style.scss
> accesstheme: remove bg-light style tweak in favor of md-full-width

- .github/workflows/backupdb.yml
- .github/workflows/behat.yml
- .github/workflows/configsync.yml
Switch to new non-caching actions.
https://cyberteamportal.atlassian.net/browse/D8-1848
> github:  d8-1848

- tests/behat/features/asp/homepage/navigation_bar_footer.feature
- tests/behat/features/bootstrap/Drupal/FeatureContext.php
- tests/behat/features/cci/cci-homepage.feature
> Behat 9-8-23 --get all tests to pass

- composer.json
- composer.lock
- web/sites/default/config/default/core.extension.yml
ga_login module was merged into tfa module
n/a
http://md-noga-accessmatch.pantheonsite.io
> Uninstall ga_login and use tfa

- web/themes/custom/accesstheme/templates/page.html.twig
The "Acceptable Use" Title in the footer changed to "Acceptable Use Policy" and the Link destination was changed to "/acceptable-use/"
https://cyberteamportal.atlassian.net/browse/D8-1845
http://md-1845-accessmatch.pantheonsite.io
> Changing Acceptable Use footer link and title

- web/themes/custom/accesstheme/templates/page.html.twig
- web/themes/nect-theme/templates/page.html.twig
remove usersnap script (removes feedback button) 
https://cyberteamportal.atlassian.net/browse/D8-1846
same for campus campions theme
http://md-1846-accessmatch.pantheonsite.io
- [x ] I have checked that the PR is ready to be merged
- [ x] I have reviewed the DIFF and checked that the changes are as expected
- [x ] I have assigned myself or someone else to review the PR
> remove usersnap script (removes feedback button) d8-1846

- tests/behat/features/templates/affinity_groups/affinity_group.feature
- web/sites/default/config/default/views.view.people_all.yml
add pages and data exports for people in regions:
nect, campus champions, careers
https://cyberteamportal.atlassian.net/browse/D8-1853
http://md-1853-accessmatch.pantheonsite.io
- [ x] I have checked that the PR is ready to be merged
- [x ] I have reviewed the DIFF and checked that the changes are as expected
- [ x] I have assigned myself or someone else to review the PR
> Data export pages - md-1853

- .gitignore
- .lando.yml
- tests/cypress/cypress.config.js
- tests/cypress/cypress/e2e/admin-service-alert.cy.js
- tests/cypress/cypress/fixtures/example.json
- tests/cypress/cypress/fixtures/login-data.json
- tests/cypress/cypress/support/commands.js
- tests/cypress/cypress/support/e2e.js
- tests/cypress/package-lock.json
- tests/cypress/package.json
Adding lando commands for cypress, and basic cypress directory.
> Lando cypress

- web/sites/default/config/default/block.block.champions_interestsdescription.yml
- web/sites/default/config/default/block.block.champions_skillsdescription.yml
- web/sites/default/config/default/block.block.interestsdescription.yml
- web/sites/default/config/default/block.block.requesttagbutton.yml
- web/sites/default/config/default/block.block.requesttagbutton_2.yml
- web/sites/default/config/default/block.block.requesttagbuttonasp.yml
- web/sites/default/config/default/block.block.skillsdescription.yml
Add button to “Add Interests” and “Add Expertise” pages linking to form to request a new tag.
https://cyberteamportal.atlassian.net/browse/D8-1537
http://md-1537b-accessmatch.pantheonsite.io
> Adding in Request Tag and Fixing descriptions

- tests/behat/features/asp/community_persona.feature
- tests/behat/features/asp/engagements/match-engagements-submissions-auth.feature
- tests/behat/features/asp/engagements/match-plus_verify-engagement-flow.feature
- tests/behat/features/asp/engagements/match-premier-auth.feature
- tests/behat/features/asp/engagements/match-premier_verify-engagment-flow.feature
- tests/behat/features/bootstrap/Drupal/FeatureContext.php
Updates to engagement tests, to reflect changes to the engagement forms. 
https://cyberteamportal.atlassian.net/browse/D8-1860
> D8 1860  behat add ck rich text verification

- tests/behat/features/asp/engagements/match-plus-unauth.feature
- tests/behat/features/bootstrap/Drupal/FeatureContext.php
> D8-1860 followup - one behat line was "undefined" -- fixed that, but needed to update logic

- tests/behat/features/asp/cssn/cssn.feature
Fixing failing tests in md-dev
> Md fixingdev

- composer.json
- composer.lock
- web/sites/default/config/default/content_moderation_notifications.content_moderation_notification.engagement_review_requested.yml
match role changes - md 1368
https://cyberteamportal.atlassian.net/browse/D8-1368
Matching access:  d8-1368
http://md-1368-accessmatch.pantheonsite.io
- [x ] I have checked that the PR is ready to be merged
- [ x] I have reviewed the DIFF and checked that the changes are as expected
- [ x] I have assigned myself or someone else to review the PR
> match role changes - Md-1368

- .github/workflows/cypress.yml
- tests/cypress/cypress/e2e/accessmatch/asp.cy.js
> Jasper cypress add asp test to accessmatch

- .github/workflows/cypress.yml
> simplifying to just asp

- tests/cypress/cypress.config.js
- tests/cypress/cypress/e2e/accessmatch/1-smoke-test.js
- tests/cypress/cypress/e2e/accessmatch/asp-homepage.cy.js
- tests/cypress/cypress/e2e/accessmatch/asp.cy.js
- tests/cypress/cypress/e2e/admin-service-alert.cy.js
- tests/cypress/cypress/e2e/amp.cy.js
- tests/cypress/cypress/e2e/nect.cy.js
- tests/cypress/cypress/support/commands.js
- tests/cypress/cypress/support/e2e.js
> Cypress jasper 2023 10 2

- .github/workflows/cypress.yml
> update cypress action to use new slack channel

- tests/behat/features/templates/tags/tags-auth.feature
- web/sites/default/config/default/views.view.tags_hierarchal.yml
Fixing the Tags Tree View to open the collapse when the top level tag is clicked
https://cyberteamportal.atlassian.net/browse/D8-1858
http://md-1858-accessmatch.pantheonsite.io
> Fixing Tags Tree View

- web/sites/default/config/default/views.view.projectsubmission.yml
- web/sites/default/config/default/webform.webform.project.yml
Adding the Career SC role to have access to the project submissions view
https://cyberteamportal.atlassian.net/browse/D8-1834
http://md-1834-accessmatch.pantheonsite.io
> Adding Career SC role to project submissions view

- .github/workflows/cypress.yml
> trying for cypress slack notifications

- composer.json
- composer.lock
- web/sites/default/config/default/block.block.accessresourcespageintro.yml
- web/sites/default/config/default/block.block.accesstheme_help.yml
- web/sites/default/config/default/block.block.accesstheme_local_actions.yml
- web/sites/default/config/default/block.block.accesstheme_local_tasks.yml
- web/sites/default/config/default/block.block.accesstheme_messages.yml
- web/sites/default/config/default/block.block.exposedformresourcespage_1_2.yml
- web/sites/default/config/default/block.block.interestsdescription_2.yml
- web/sites/default/config/default/block.block.newsandeventsblock.yml
- web/sites/default/config/default/block.block.skillsdescription_2.yml
- web/sites/default/config/default/block.block.ticketingchoices.yml
- web/sites/default/config/default/block.block.views_block__match_engagement_view_block_5.yml
- web/sites/default/config/default/block.block.views_block__resources_block_1_2.yml
- web/sites/default/config/default/block.block.views_block__tagged_news_block_block_1.yml
- web/sites/default/config/default/block.block.welcometothecssn.yml
- web/sites/default/config/local/block.block.userlogin.yml
- web/themes/custom/accesstheme/templates/page.html.twig
New create ticket page with choices. If user logged in, sends account name and display in url parameters. If not,
sends blanks.  
https://cyberteamportal.atlassian.net/browse/D8-1363
amp/access
Note the branch name ends in "a"
http://md-1363a-accessmatch.pantheonsite.io
> ticketing choices page md-1363a

- .github/workflows/cypress.yml
- tests/cypress/cypress/e2e/asp.cy.js
> Cypress GitHub action update

- .github/workflows/cypress.yml
> tweak cypress notification

- .github/workflows/cypress.yml
> investigating why cypress tests don't run

- .github/workflows/behat.yml
> remove asp from behat runs

- composer.json
- composer.lock
New theme: Match Engagement Guide page d8-1872
https://cyberteamportal.atlassian.net/browse/D8-1872
https://github.com/necyberteam/access/pull/151
http://md-th1872-accessmatch.pantheonsite.io/match-engagement-guide
> New theme: Match Engagement Guide page d8-1872

- .github/workflows/cypress.yml
> remove diagnostic

- .github/workflows/cypress.yml
> adding broken-links job

- .github/workflows/cypress.yml
> revert change for broken-links

- web/sites/default/config/default/block.block.userlogin_2.yml
Adding in a login page that will be used for testing purposes only
http://md-login-accessmatch.pantheonsite.io
> Adding in login page for testing

- .github/workflows/backupdb.yml
- tests/cypress/cypress/e2e/accessmatch/ci-link-admin-add-a-test-ci-link.cy.js
- tests/cypress/cypress/e2e/accessmatch/verify-test-users.cy.js
Modifying github workflow to create 2 users for testing
> GitHub workflow add users

- .github/workflows/backupdb.yml
> add creation of 2 test users to github workflows

- tests/behat/features/asp/affinity-groups/affinity_groups-individual.feature
- tests/behat/features/asp/asp-ci-links/ci-links-submission-process.feature
- tests/behat/features/templates/affinity_groups/affinity_group.feature
- tests/behat/features/templates/ci-links/ci-links-submission-process.feature
- tests/behat/features/templates/homepage/homepage_edit-account-auth.feature
- tests/behat/features/templates/tags/tags-individual.feature
Fixing broken test for cyberteams and asp test
#974 
> Fixing broken test and brackets test

- tests/cypress/cypress/e2e/accessmatch/contact-send-email-form.cy.js
- tests/cypress/cypress/e2e/accessmatch/help-ticket.cy.js
- tests/cypress/cypress/e2e/accessmatch/knowledge-base/knowledge-base.cy.js
Couple more tests, tests of knowledge-base page, and user/contact
Ready for review
> Cypress jasper 11 03 23 - tests of knowledge-base page, and user/contact

- tests/cypress/cypress/e2e/accessmatch/affinity-groups/ag-individual-group-anon.cy.js
- tests/cypress/cypress/e2e/accessmatch/affinity-groups/ag-page-images.cy.js
- tests/cypress/cypress/e2e/accessmatch/asp-homepage.cy.js
- tests/cypress/cypress/e2e/accessmatch/knowledge-base/knowledge-base.cy.js
- tests/cypress/cypress/e2e/accessmatch/outgages.cy.js
- tests/cypress/cypress/e2e/accessmatch/tags/tags.cy.js
- tests/cypress/cypress/support/commands.js
- web/sites/default/config/default/domain.record.amp_cyberinfrastructure_org.yml
- web/sites/default/config/default/domain.record.nectd8_wpi_edu.yml
> more tests, esp. tags

- tests/cypress/cypress/e2e/accessmatch/find.cy.js
> test of /find

- tests/cypress/cypress/e2e/accessmatch/knowledge-base/knowledge-base.cy.js
- tests/cypress/cypress/e2e/accessmatch/tags/tag-individual-engagements.cy.js
- tests/cypress/cypress/e2e/accessmatch/tags/tag-individual.cy.js
- tests/cypress/cypress/e2e/accessmatch/webforms/admin-create-ci-link.cy.js
test of individual tag page
ready for review
> test of individual tag page

- tests/cypress/cypress/e2e/accessmatch/asp-homepage.cy.js
- tests/cypress/cypress/support/commands.js
> redo of cta

- web/sites/default/config/default/views.view.match_engagements_submissions.yml
Fix duplicates in view.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1895
https://md-1895-accessmatch.pantheonsite.io/match-engagements-submissions
> config: views distinct

- blt/md/domains.json
- blt/src/Blt/Plugin/Commands/AmpCommands.php
Adding the json list of domains to a file because the drush command has been taking 4-ish minutes to run.
https://cyberteamportal.atlassian.net/browse/D8-1949
> blt: ds and mds added json file to cache domains d8-1949

- tests/cypress/cypress/e2e/accessmatch/affinity-groups/ag-individual-group-admin.cy.js
- tests/cypress/cypress/e2e/accessmatch/affinity-groups/ag-individual-group-auth.cy.js
- tests/cypress/cypress/e2e/accessmatch/webforms/admin-create-ci-link.cy.js
- web/sites/default/config/default/core.entity_form_display.node.access_news.default.yml
- web/sites/default/config/default/mailsystem.settings.yml
- web/sites/default/config/local/mailsystem.settings.yml
Updated weights on acces_news for form display.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1925
http://md-1925-accessmatch.pantheonsite.io
> config: access_news change form display weights d8-1925

- tests/cypress/cypress/e2e/accessmatch/affinity-groups/ag-individual-group-admin.cy.js
- tests/cypress/cypress/e2e/accessmatch/affinity-groups/ag-individual-group-auth.cy.js
- tests/cypress/cypress/e2e/accessmatch/webforms/admin-create-ci-link.cy.js
- web/sites/default/config/default/mailsystem.settings.yml
- web/sites/default/config/default/webform.webform.join_the_cssn_network.yml
- web/sites/default/config/local/mailsystem.settings.yml
Fix 'Join CSSN' webform block styles.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1942
https://md-1942-accessmatch.pantheonsite.io/community/cssn
> Join CSSN Webform: update classes/styles d8-1942

- web/sites/default/config/default/user.role.authenticated.yml
- web/sites/default/config/local/user.role.anonymous.yml
> Remove devel switch users permission

- composer.json
- composer.lock
- tests/cypress/cypress/e2e/accessmatch/announcements/announcement-form.cy.js
- tests/cypress/cypress/e2e/accessmatch/announcements/announcements-page.cy.js
Remove menu_per_role module.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1954
> menu_per_role: removed

- composer.lock
> Update access theme and module

- composer.lock
> Update access module and theme

- web/sites/default/config/default/views.view.people_filter_emails.yml
Adding view with a bunch of filters to get emails.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1963
http://md-1963-accessmatch.pantheonsite.io
> config: people_filter_emails view added d8-1963

- composer.json
- composer.lock
Add color to accordion shortcode
so Match Engagement Guide can have accordion with white-background summary
https://cyberteamportal.atlassian.net/browse/D8-1953
http://md-1953-accessmatch.pantheonsite.io
> Add color to accordion shortcode d8-1953

- web/sites/default/config/default/views.view.node_add_tags.yml
Add tags to Find page
The following changes need to be done to the content for basic page /Find
- Edit the html to change pb-20 to pb-0
- Edit the layout to add a section with the new block (in Lists)  All Tags Block
(todo: to understand out current dev process for updating content)
https://cyberteamportal.atlassian.net/browse/D8-1952
http://md-1952-accessmatch.pantheonsite.io
> Add tags to Find page

- composer.json
- composer.lock
http://md-comp19-accessmatch.pantheonsite.io
> Ingest ACCESS Org with daily cron

- web/sites/default/config/default/views.view.affinity_group.yml
Add `tags` label to table on affinity groups
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1961
> views affinity_group add tags label d8-1961

- web/sites/default/config/default/views.view.match_engagement_view.yml
Match view switched to distinct to remove duplicates.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1969
http://md-1969-accessmatch.pantheonsite.io
> views match_engagment switch to disinct d8-1969

- tests/cypress/cypress/e2e/accessmatch/tags/tags.cy.js
- web/sites/default/config/default/block.block.skillsdescription.yml
- web/sites/default/config/default/views.view.add_interest.yml
- web/sites/default/config/default/views.view.add_skill.yml
- web/sites/default/config/default/views.view.node_add_tags.yml
- web/sites/default/config/default/views.view.tags.yml
Add prose class to tags pages to fix layout.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1977
http://md-1977-accessmatch.pantheonsite.io
> config: tag views add prose class d8-1977

- web/sites/default/config/default/block.block.nect_exposedformorganizationorganization_card.yml
- web/sites/default/config/default/block.block.views_block__organization_block_1.yml
- web/sites/default/config/default/block.block.views_block__organization_organization_card.yml
- web/sites/default/config/default/pathauto.pattern.organizations.yml
- web/sites/default/config/default/views.view.organization.yml
- web/themes/nect-theme/css/style.css
http://md-1982-accessmatch.pantheonsite.io
> Exposed filter for CoCo front page (Organizations view)

- composer.lock
- tests/behat/features/templates/tags/tags-auth.feature
- tests/behat/features/templates/tags/tags-unauth.feature
> Fix outages on Affinity Groups

- web/modules/custom/campuschampions/campuschampions.routing.yml
- web/modules/custom/campuschampions/src/Form/RemoveChampionForm.php
> Add form for CampusChampionsAdmins to be able to remove Campus Champions

- composer.lock
> Update access module

- composer.patches.json
- tests/behat/features/templates/tags/tags-auth.feature
- tests/behat/features/templates/tags/tags-request-auth.feature
- tests/behat/features/templates/tags/tags-unauth.feature
Update pager patch.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-1998
http://md-1998-accessmatch.pantheonsite.io
> d8-1998 drupal: update pager patch

- composer.lock
- composer.patches.json
Update recurring_events and remove patch
https://cyberteamportal.atlassian.net/browse/D8-2017
http://md-2017-accessmatch.pantheonsite.io
> recurring_events: 2.0.0 => 2.0.1 - patch removed

- composer.json
- composer.lock
- tests/behat/features/templates/tags/tags-auth.feature
- tests/behat/features/templates/tags/tags-request-auth.feature
- tests/behat/features/templates/tags/tags-unauth.feature
- tests/cypress/cypress/e2e/accessmatch/tags/tag-individual.cy.js
- tests/cypress/package-lock.json
- tests/cypress/package.json
- web/sites/default/config/default/views.view.added_interests.yml
- web/sites/default/config/default/views.view.added_skills.yml
- web/themes/nect-theme/templates/views-view--added_interests--block_2.html.twig
- web/themes/nect-theme/templates/views-view--added_skills--block_3.html.twig
Add custom "more" text for tags list on user profiles on tags result page  d8-1959.
Changed views and altered twig files.
https://cyberteamportal.atlassian.net/browse/D8-1959
https://github.com/necyberteam/aspTheme/pull/29
https://github.com/necyberteam/campus-champions-theme/pull/8
http://md-1959-accessmatch.pantheonsite.io
> Add custom "more" text for tags list on user profiles on tags result page  d8-1959

- composer.json
- composer.lock
https://cyberteamportal.atlassian.net/browse/D8-2021
https://github.com/necyberteam/campus-champions-theme/pull/11
http://md-2021-accessmatch.pantheonsite.io
> Campus Champions login form style fix d8-2021

- composer.json
- composer.lock
Long links break mobile layout 
Change in asp-theme; this is just to require the theme branch
https://cyberteamportal.atlassian.net/browse/D8-2056
https://github.com/necyberteam/aspTheme/pull/34
http://md-2056-accessmatch.pantheonsite.io
> long links break mobile layout d8-2056

- web/sites/default/config/default/contact.form.ccmnet.yml
https://cyberteamportal.atlassian.net/browse/D8-2058
http://md-2058-accessmatch.pantheonsite.io
> Contact form for ccmnet d8-2058

- web/themes/nect-theme/css/style.css
> Button style

- composer.lock
- tests/cypress/cypress/e2e/accessmatch/affinity-groups/ag-anon.cy.js
- web/sites/default/config/default/content_moderation_notifications.content_moderation_notification.engagement_draft.yml
- web/sites/default/config/default/content_moderation_notifications.content_moderation_notification.final_review.yml
- web/sites/default/config/default/views.view.match_engagements_submissions.yml
- web/themes/nect-theme/css/style.css
> Update selected tag style

- web/sites/default/config/default/views.view.mentorship_status.yml
New Mentorship Status view 
https://cyberteamportal.atlassian.net/browse/D8-2086
http://md-2086-accessmatch.pantheonsite.io
> Mentorship Status view d8-2086

- web/sites/default/config/default/core.entity_view_display.node.mentorship_engagement.teaser.yml
- web/sites/default/config/default/views.view.mentorship_facet_search.yml
- web/themes/nect-theme/css/style.css
- web/themes/nect-theme/templates/views-view-unformatted--mentorship_facet_search--block_1.html.twig
Home page for CCMNet
https://cyberteamportal.atlassian.net/browse/D8-2059
http://md-2059-accessmatch.pantheonsite.io
> ccmnet front page view/style tweaks d8-2059

- composer.json
- composer.lock
https://cyberteamportal.atlassian.net/browse/D8-2080
https://github.com/necyberteam/access/pull/211
http://md-2080-accessmatch.pantheonsite.io
> mentorship interest email to have ccmnet.org on links d8-2080 

- composer.json
- composer.lock
https://github.com/necyberteam/access/pull/212
http://md-2096-accessmatch.pantheonsite.io
> mentorship page - interested user persona link -- d8-2096

- web/themes/nect-theme/css/style.css
Hide details arrow on nect-theme.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-2115
> nect: hide details arrow d8-2115

- web/themes/nect-theme/css/style.css
Fix color for selected skills/tags.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-2103
> nect: add white color for skills/tags d8-2103

- web/themes/nect-theme/css/style.css
Fix colors/sizes on skills/interests on ccmnet
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-2103
> netct: skills/interest css updates d8-2103

- web/sites/default/config/default/nect.settings.yml
Update careers button
https://cyberteamportal.atlassian.net/browse/D8-2118
> config: update careers button d8-2118

- tests/cypress/cypress/e2e/accessmatch/asp-homepage.cy.js
- tests/cypress/cypress/e2e/accessmatch/knowledge-base/knowledge-base.cy.js
- tests/cypress/cypress/e2e/accessmatch/tags/tag-individual.cy.js
- web/sites/default/config/default/views.view.access_news.yml
- web/sites/default/config/default/views.view.recurring_events_event_instances.yml
Access front page text tweaks
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-2130
http://md-2130-accessmatch.pantheonsite.io
> config: views text updates d8-2130

- composer.lock
- web/themes/nect-theme/css/style.css
> SimpleLists Affinity Group update

- composer.json
- composer.lock
Fix persona sidebar width. All of the changes are in asp-theme, this PR can be disregarded.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-2161
https://github.com/necyberteam/aspTheme/pull/41
http://md-2161-accessmatch.pantheonsite.io
> asp-theme: dev-main d4a280a => dev-d8-2161 578c375

- composer.json
- composer.lock
https://cyberteamportal.atlassian.net/browse/D8-2011
https://github.com/necyberteam/access/pull/235
http://md-2011-accessmatch.pantheonsite.io
> Infrastructure News broadcast to Constant Contact

- blt/md/md-2166
- composer.json
- composer.lock
- web/sites/default/config/default/views.view.recurring_events_event_instances.yml
https://cyberteamportal.atlassian.net/browse/D8-2166
http://md-2166-accessmatch.pantheonsite.io
> Search upcoming events

- composer.lock
- web/sites/default/config/default/core.entity_view_display.node.access_news.default.yml
Fix sidebar headers on announcements pages. This is already changed on prod, and this brings in the config change.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-2163
> config: access_news layout display updated d8-2163

- web/sites/default/config/default/nect.settings.yml
> Update CCMNet front page text

- composer.patches.json
- web/sites/default/config/default/views.view.event_instances_api.yml
https://cyberteamportal.atlassian.net/browse/D8-2189
http://md-2183-accessmatch.pantheonsite.io
> Event API (Md 2189)

- composer.json
- composer.lock
Deny access to non CCMNet domains from creating mentorships.
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-2191
https://github.com/necyberteam/access/pull/242
http://md-2191-accessmatch.pantheonsite.io
> access: 3.0.x-dev 86da55b => dev-d8-2191 bced829

- web/sites/default/config/default/views.view.affinity_group.yml
- web/sites/default/config/default/views.view.affinity_group_card_view.yml
Remove duplicates in the view
https://cyberteamportal.atlassian.net/browse/D8-2190
https://md-2190-accessmatch.pantheonsite.io
> config: ag card view switch to distinct d8-2190

- web/sites/default/config/default/block.block.asptheme_qatool.yml
- web/sites/default/config/default/core.entity_view_display.node.mentorship_engagement.default.yml
- web/sites/default/config/default/fontawesome.settings.yml
- web/sites/default/config/default/rules.reaction.new_user.yml
> Update config settings

- web/sites/default/config/default/core.extension.yml
> Enable badges module

- web/sites/default/config/default/views.view.cssn_directory.yml
Sort CSSN directory by last name, first name
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-2235
> config: cssn dir view sort order switched d8-2235

- web/sites/default/config/default/views.view.access_news.yml
Announcements Excerpt Formatting
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-2208
http://md-2208-accessmatch.pantheonsite.io
> config: access_news add <p> to summary

- tests/cypress/cypress/e2e/accessmatch/events/events-add.cy.js
- web/sites/default/config/default/core.entity_form_display.eventseries.default.default.yml
- web/sites/default/config/default/core.entity_view_display.eventinstance.default.default.yml
- web/sites/default/config/default/field.storage.eventseries.field_affiliation.yml
Recurring Event Affiliation field should accept unlimited values
https://cyberteamportal.atlassian.net/jira/software/c/projects/D8/issues/D8-2245
http://md-2245-accessmatch.pantheonsite.io
> config: switch affiliation to unlimited

- composer.lock
> Update facets, tfa, and composer

- web/sites/default/config/default/field.storage.node.field_infrastructure_news_type.yml
Infrastructure News validation
https://cyberteamportal.atlassian.net/browse/D8-2279
<over limit>
http://md-2279-accessmatch.pantheonsite.io
> config: infrastructure news adding new type d8-2279

- composer.patches.json
- patches/3207813-27.patch
Add patch: https://www.drupal.org/project/drupal/issues/3207813#comment-14962228
https://cyberteamportal.atlassian.net/browse/D8-2284
http://md-2284-accessmatch.pantheonsite.io
> composer: adding patch d.0/node/3207813 d8-2284

- composer.lock
> Update ACCESS theme

- blt/lando.local.settings.php
- composer.json
- composer.lock
- robo/assets/lando.local.settings.php
- web/sites/default/config/default/core.extension.yml
- web/sites/default/settings.php
http://md-ratelim-accessmatch.pantheonsite.io
> Crawler rate limiting

- web/sites/default/config/default/content_moderation_notifications.content_moderation_notification.published.yml
- web/sites/default/config/default/workflows.workflow.editorial_eventinstance.yml
Event series: sending many note emails upon publish
https://cyberteamportal.atlassian.net/browse/D8-1115
http://md-1115-accessmatch.pantheonsite.io
> config: workflow

- composer.lock
> Update to Drupal 10.4.3

- composer.lock
content_moderation_notifications : 3.6.0 => 3.7.0
> [Composer] drupal/content_moderation_notifications

- composer.lock
block_exclude_pages : 2.1.1 => 2.1.2
> [Composer] drupal/block_exclude_pages

- composer.lock
upgrade_status : 4.2.0 => 4.3.6
> [Composer] drupal/upgrade_status

- composer.lock
> [Composer] drupal/gtm

- composer.lock
layout_builder_styles : 2.0.0 => 2.1.0
> [Composer] drupal/layout_builder_styles

- composer.lock
image_captcha : 2.0.5 => 2.0.7 — image_captcha : 2.0.5 => 2.0.7
> [Composer] drupal/image_captcha

- composer.lock
domain_access : 2.0.0-beta1 => 2.0.0-beta2 — domain_access : 2.0.0-beta1 => 2.0.0-beta2
> [Composer] drupal/domain_access

- composer.lock
devel_kint_extras : 1.1.1 => 1.1.3
> [Composer] drupal/devel_kint_extras

- composer.lock
access_by_ref : 3.0.1 => 3.0.3
> [Composer] drupal/access_by_ref

- composer.lock
inline_entity_form : 3.0.0-rc19 => 3.0.0-rc20
> [Composer] drupal/inline_entity_form

- composer.json
- composer.lock
fieldblock : 2.2.0 => 2.3.0 — browser-kit : v6.4.13 => v6.4.19 — dependency-injection : v6.4.16 => v6.4.19 — dom-crawler : v6.4.18 => v6.4.19 — error-handler : v6.4.18 => v6.4.19 — http-client : v6.4.18 => v6.4.19 — http-kernel : v6.4.18 => v6.4.19 — mime : v6.4.18 => v6.4.19 — process : v6.4.15 => v6.4.19 — serializer : v6.4.18 => v6.4.19 — translation : v7.2.2 => v7.2.4 — validator : v6.4.18 => v6.4.19 — var-exporter : v6.4.13 => v6.4.19
> [Composer] drupal/fieldblock

- composer.json
- composer.lock
> [Composer] drupal/file_delete

- .github/workflows/cypress.yml
- composer.json
- composer.lock
> [Composer] drupal/honeypot

- composer.lock
> [Composer] drupal/redirect

- .github/workflows/cypress.yml
- composer.lock
> [Composer] drupal/examples

- composer.lock
> [Composer] drupal/menu_block

- composer.lock
pantheon_advanced_page_cache : 2.2.0 => 2.3.2
> [Composer] drupal/pantheon_advanced_page_cache

- composer.lock
> [Composer] drupal/tfa

- .github/workflows/cypress.yml
- README.md
- composer.lock
flag : 4.0.0-beta4 => 4.0.0-beta6
> [Composer] drupal/flag

- composer.lock
user_current_paths : 2.0.3 => 2.0.4
> [Composer] drupal/user_current_paths

- composer.lock
> [Composer] drupal/shortcode

- README.md
- tests/cypress/cypress/e2e/templates/affinity_groups/affinity_group.cy.js
http://md-1047-accessmatch.pantheonsite.io
> Run Cypress tests on Drupal 10.4.5 

- composer.lock
drupal_seamless_cilogon : 3.0.x-dev 2000bd5 => 3.0.x-dev c398560
> [Composer] access/drupal_seamless_cilogon

- composer.lock
realname : 2.0.0-beta2 => 2.0.0
> [Composer] drupal/realname #nobuild

- composer.lock
> [Composer] drupal/real_aes #nobuild

- composer.lock
private_files_download_permission : 3.1.1 => 3.1.3
> [Composer] drupal/private_files_download_permission #nobuild

- composer.lock
> [Composer] drupal/redis #sync

- composer.lock
> [Composer] drupal/pathauto #nobuild

- web/sites/default/config/default/search_api.index.mentorship_engagement.yml
> Don't check content access for mentorships search api

- composer.lock
> [Composer] drupal/datalayer #nobuild

- composer.lock
> [Composer] drupal/devel #nobuild

- composer.lock
devel_kint_extras : 1.1.3 => 1.1.4
> [Composer] drupal/devel_kint_extras #nobuild

- composer.lock
easy_breadcrumb : 2.0.6 => 2.0.9
> [Composer] drupal/easy_breadcrumb #nobuild

- composer.lock
feeds : dev-3.x 5f2fe3a => dev-3.x ea64d3b
> [Composer] drupal/feeds #nobuild

- composer.lock
> [Composer] drupal/field_group #nobuild

- composer.lock
field_permissions : 1.3.0 => 1.4.0
> [Composer] drupal/field_permissions #sync

- web/sites/default/config/default/block.block.nect_joinccmnet.yml
- web/themes/nect-theme/css/style.css
> Join block adjustments

- composer.lock
> [Composer] drupal/imce #nobuild

- composer.lock
label_help : 2.0.0-rc1 => 2.0.0-rc2
> [Composer] drupal/label_help #nobuild

- composer.lock
masquerade : 2.0.0-rc4 => 2.0.0
> [Composer] drupal/masquerade #nobuild

- composer.lock
menu_item_extras : 3.0.2 => 3.1.0
> [Composer] drupal/menu_item_extras #nobuild

- composer.lock
menu_item_role_access : 2.1.0 => 2.4.0
> [Composer] drupal/menu_item_role_access

- composer.lock
menu_link_attributes : 1.3.0 => 1.5.0
> [Composer] drupal/menu_link_attributes #nobuild

- composer.lock
> [Composer] drupal/mailsystem #nobuild

- composer.lock
symfony_mailer : 1.4.1 => 1.5.0
> [Composer] drupal/symfony_mailer #nobuild

- composer.lock
views_aggregator : 2.0.2 => 2.1.1
> [Composer] drupal/views_aggregator

- composer.lock
views_bulk_operations : 4.2.6 => 4.3.4
> [Composer] drupal/views_bulk_operations #nobuild

- composer.lock
> [Composer] mglaman/drupal-check

- composer.lock
views_contextual_filters_or : 1.4.0 => 1.5.0
> [Composer] drupal/views_contextual_filters_or #nobuild

- composer.lock
views_sort_options_weight : 2.1.1 => 2.2.0
> [Composer] drupal/views_sort_options_weight #nobuild

- composer.lock
views_field_view : 1.0.0-beta5 => 1.0.0-beta6
> [Composer] drupal/views_field_view #nobuild

- composer.lock
domain_source : 2.0.0-beta1 => 2.0.0-beta2 — domain_source : 2.0.0-beta1 => 2.0.0-beta2
> [Composer] drupal/domain_source #nobuild

- composer.lock
domain_theme_switch : 2.0.0 => 2.1.0
> [Composer] drupal/domain_theme_switch

- composer.lock
domain_site_settings : 1.5.0 => 1.6.0
> [Composer] drupal/domain_site_settings #nobuild

- composer.lock
> [Composer] drupal/social_api #nobuild

- composer.lock
> [Composer] drupal/social_auth #nobuild

- composer.lock
domain_config : 2.0.0-beta1 => 2.0.0-beta2 — domain_config : 2.0.0-beta1 => 2.0.0-beta2
> [Composer] drupal/domain_config #nobuild

- composer.lock
> [Composer] drupal/readonlymode #nobuild

- composer.lock
> [Composer] drupal/stable

- composer.lock
> [Composer] drupal/restui #nobuild

- web/sites/default/config/default/views.view.mentorship_status.yml
Add "In Progress and Recruiting" state to mentorship_status view.
> Add "In Progress and Recruiting" state to mentorship_status view.

- web/sites/default/config/default/views.view.mentorship_facet_search.yml
Add "In Progress and Recruiting" state to filter
> Add "In Progress and Recruiting" state to Mentorship filter

- composer.json
- composer.lock
deprecations : 1.1.4 => 1.1.5 — filter_perms : 1.0.0-alpha2 => 2.0.2 — email-validator : 4.0.3 => 4.0.4 — guzzle : 7.9.2 => 7.9.3 — psr7 : 2.7.0 => 2.7.1 — laminas-escaper : 2.16.0 => 2.17.0 — deep-copy : 1.13.0 => 1.13.1 — reflection-docblock : 5.6.1 => 5.6.2 — prophecy : v1.20.0 => v1.22.0 — phpunit : 9.6.22 => 9.6.23 — console : v6.4.17 => v6.4.21 — dependency-injection : v6.4.19 => v6.4.20 — error-handler : v6.4.19 => v6.4.20 — http-foundation : v6.4.18 => v6.4.21 — http-kernel : v6.4.19 => v6.4.21 — mailer : v6.4.18 => v6.4.21 — mime : v6.4.19 => v6.4.21 — polyfill-php73 : v1.31.0 => v1.32.0 — polyfill-php80 : v1.31.0 => v1.32.0 — polyfill-php81 : v1.31.0 => v1.32.0 — process : v6.4.19 => v6.4.20 — serializer : v6.4.19 => v6.4.21 — string : v6.4.15 => v6.4.21 — validator : v6.4.19 => …
> [Composer] drupal/filter_perms

- composer.lock
inline_entity_form : 3.0.0-rc20 => 3.0.0-rc21
> [Composer] drupal/inline_entity_form #sync

- composer.lock
> Update to Drupal 10.4.7

- composer.lock
auditfiles : 4.1.0-beta2 => 4.2.1
> [Composer] drupal/auditfiles

- composer.json
- composer.lock
csv_serialization : 3.0.0 => 4.0.1 — csv : 9.15.0 => 9.23.0
> [Composer] drupal/csv_serialization

- composer.lock
> [Composer] drupal/captcha

- composer.lock
> [Composer] drupal/ctools

- composer.lock
better_exposed_filters : 6.0.5 => 6.0.6
> [Composer] drupal/better_exposed_filters

- composer.json
- composer.lock
config_filter : 1.13.0 => 2.7.0 — laminas-feed : 2.23.0 => 2.23.1
> [Composer] drupal/config_filter #nobuild

- composer.lock
role_delegation : 1.2.0 => 1.3.0
> [Composer] drupal/role_delegation #nobuild

- composer.json
- composer.lock
mail_login : 3.0.0 => 4.0.3 — laminas-feed : 2.23.0 => 2.23.1
> [Composer] drupal/mail_login #nobuild

- composer.json
- composer.lock
> [Composer] drupal/captcha #nobuild

- composer.json
- composer.lock
better_exposed_filters : 6.0.6 => 7.0.5
> [Composer] drupal/better_exposed_filters #nobuild

- composer.lock
> [Composer] drupal/yaml_editor #nobuild

- composer.lock
search_exclude : 3.0.0-beta1 => 3.0.0-beta2
> [Composer] drupal/search_exclude #nobuild

- composer.json
- composer.lock
installers : v1.12.0 => v2.3.0
> [Composer] composer/installers

- composer.lock
> [Composer] drupal/search_api

- .github/actions/ddev-base/action.yml
- .github/actions/dingorunner/entrypoint.sh
- .github/workflows/backupdb.yml
- composer.json
- composer.lock
- robo/src/Robo/Plugin/Commands/GeneralCommands.php
> [Composer] drupal/core #sync

- composer.json
- composer.lock
taxonomy_term_depth : 2.6.0 => 3.0.1 — php-parser : v5.4.0 => v5.5.0 — console : v6.4.21 => v6.4.22 — dependency-injection : v6.4.20 => v6.4.22 — error-handler : v6.4.20 => v6.4.22 — http-foundation : v6.4.21 => v6.4.22 — http-kernel : v6.4.21 => v6.4.22 — routing : v6.4.18 => v6.4.22 — serializer : v6.4.21 => v6.4.22 — validator : v6.4.21 => v6.4.22 — var-exporter : v6.4.21 => v6.4.22
> [Composer] drupal/taxonomy_term_depth #nobuild

- composer.lock
views_data_export : 1.4.0 => 1.6.0
> [Composer] drupal/views_data_export #nobuild

- composer.lock
views_block_filter_block : 2.0.1 => 2.1.2
> [Composer] drupal/views_block_filter_block #nobuild

- composer.lock
> [Composer] drupal/mail_login

- composer.lock
- pantheon.upstream.yml
- tests/cypress/cypress/e2e/nect/nect-admin-structure.cy.js
- web/sites/default/config/default/views.view.mentorship_facet_search.yml
- web/themes/custom/ood/templates/page.html.twig
Make grant numbers links on OOD Footer
https://cyberteamportal.atlassian.net/browse/D8-2466
> d8-2466 - ood footer: add links to grant numbers

- composer.lock
> [Composer] drupal/recaptcha

- composer.lock
> [Composer] drupal/recaptcha_v3

- web/themes/nect-theme/css/style.css
Fix NECT mobile menu
https://cyberteamportal.atlassian.net/browse/D8-2501
> Fix NECT mobile menu

- composer.lock
upgrade_status : 4.3.7 => 4.3.8
> [Composer] drupal/upgrade_status #nobuild

- composer.lock
> [Composer] drupal/redis #nobuild

- composer.lock
> [Composer] drupal/kint-kint #nobuild

- composer.lock
- tests/cypress/cypress/e2e/nect/nect-admin-config.cy.js
- web/sites/default/config/default/core.entity_form_display.user.user.register.yml
- web/sites/default/config/default/multiple_registration.create_registration_page_form_config.yml
multiple_registration : 3.3.1 => 3.3.2
> [Composer] drupal/multiple_registration #nobuild

- composer.lock
> [Composer] drupal/webform

- composer.json
- composer.lock
drupal-code-generator : 3.5.0 => 3.6.1 — annotated-command : 4.10.1 => 4.10.2 — config : 2.1.2 => 3.1.1 — output-formatters : 4.6.0 => 4.6.1 — robo : 4.0.6 => 5.1.0 — site-alias : 4.1.0 => 4.1.1 — site-process : 5.4.0 => 5.4.2 — drush : 12.5.2 => 13.6.2 — container : 4.2.4 => 4.2.5 — psysh : v0.12.3 => v0.12.10
> [Composer] drush/drush #nobuild

- composer.lock
pantheon_advanced_page_cache : 2.3.2 => 2.3.3
> [Composer] drupal/pantheon_advanced_page_cache #nobuild

- composer.lock
- tests/cypress/cypress/e2e/accessmatch3/x-api/events-api.cy.js
> Update to access-ci-ui v0.11.0, better tests for events API v2.1

- composer.lock
> [Composer] drupal/facets

- composer.lock
image_captcha : 2.0.7 => 2.0.9 — image_captcha : 2.0.7 => 2.0.9
> [Composer] drupal/image_captcha #nobuild

- composer.lock
amp_dev : dev-main ba1eb15 => dev-main 640e823
> [Composer] amp/amp_dev
